### ISSUE TITLE
Evaluation does not work after installation

### ISSUE THREAD

**Issue by clstevenson** [data-forge-notebook/data-forge-notebook#22]
Installed latest version of Data Forge Notebook on my system (M2 MacbookPro running Sonoma MacOS). Tried to follow along with the tutorial video but any attempt to evaluate a cell -- even the simple `console.log(msg);` -- will not work. I get the spinning wheel that says "installing notebook, evaluating notebook" but nothing happens.

Data Forge commands seem to work fine in node at the command line.

**Comment by ashleydavis** [comment]
Can you please send me your log file so I can check it for errors.

If you start DFN, go to the `Settings` menu and choose `Open log file directory` it will open the directory that contains the file `log.log`. Please send me this file.

**Comment by clstevenson** [comment]
Sigh, now of course it is working. Not sure what the issue was.

**Comment by ashleydavis** [comment]
Ok thanks for letting me know.

If you see a problem again please let me know. Usually if there's an error happening I'll see it in the log.
