### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by joshjacobbaker** [data-forge-notebook/data-forge-notebook#4]
######################################################
Ashley Davis and I are moving our conversation from email to this issue 
concerning the implementation of Dark-Light Mode Styling with DataForge Notebook (DFN)
The below email is from Ash to Me for contextual purposes (see below)
######################################################
(Email from Ash to me...)

I thought of something you might like to help with on DFN.

I'd love to get darkmode working.  

Simple part will be to enable dark theme on Blueprintjs.

The harder part will be to make all the plugins (which don't use Blueprintjs) look nice in dark mode.

You can learn about Blueprint js here: https://blueprintjs.com/

If you are interested, open an issue on the DFN repo called "Dark mode" where we can discuss the implementation:

https://github.com/data-forge-notebook/editor-core

Cheers
Ash

---
######################################################
Disclaimer:
######################################################
For the record, this will be my first open-source contribution

I couldn't be any happier than contributing to the DataForgeNotebook (DFN) project!

This is a "kick the bucket" event in my life.

A little brown-nosing but I think it's cool how Ash is bringing DataScience to the JavaScript community.

The JavaScript-DataScience community NEEDS DataForge Notebook!

AGAIN... I've never done this before, so I'm eager to get started.

---
######################################################
Quick STAR method map of feature implementation..
######################################################

Situation: DFN currently doesn't have a Dark-and-Light-Mode-Theme (D&LMT) feature
Task: Implement D&LMT feature into DFN with either existing or new CSS architecture
Action: 
- Discovery: Learn about current project CSS architecture, 3rd party components like blueprintjs, etc. & other plugins styling...
- Questions: Has this been done before? How'd they do it? 
- Brainstorm: Find & compare potential CSS styling solutions that will support the on-going development of DFN
- Fork: Implement an agreed upon CSS styling architecture 
- Pull request: Merge our Fork into Master 
Result: We successfully implemented Dark-and-Light-Theme (D&LMT) feature throughout the DFN component tree 

---
######################################################
A few different possible solutions that come to mind...
######################################################
Context provider wrapper around the root component that passes state to sub-components to change styling when button toggled

TailwindCSS Dark Mode pseudo class 
i.e. dark:text-black-100 
or 
classic classes 
i.e. .darkmode {color: black}, .lightmode{color: white}
or
SASS (it's my understanding that blueprintjs uses SASS for their component styling..)
.block-element-modifier {color: $pt-dark-icon-color}
https://blueprintjs.com/docs/#core/variables.dark-theme-styles
or 
styled-components 
div(blueprintjs)`
  ${props => props.dark && css`
    background: white;
    color: black;
  `}
`
or 

---
######################################################
Blueprintjs Components & Styling
######################################################
Resource: https://blueprintjs.com/docs/#core/variables.dark-theme-styles

It looks as though Blueprintjs uses SASS styling to style their components
---
######################################################
Closing thoughts and feature discussion kickoff
######################################################

This is the beginning of what's to come!
I'm excited to start.
There are SO many ways to implement this.
The floor is open to discussion.
I'm an open-book.
Officially submitting this issue!

Cheers,
Josh
---

**Comment by ashleydavis** [comment]
This issue hasn't really been useful so far, although dark mode is still needed. I'll open a new ticket.
